### PR TITLE
tx: fix the number of pages is incorrectly counted

### PR DESCRIPTION
**Pull request by zrss**
tx: PageCount add up the count that we try to allocate

### CODE REVIEW

**Comment by xiang90** [comment]
@zrss can you add a test for this fix? thanks.

**Comment by zrss** [comment]
@xiang90 

i add an accessible method for `tx.allocate`, and do not close the db file with `MustClose` method to skip `MustCheck`

**Comment by gyuho** [comment]
Why not creating another unit test file rather than exposing `allocate` method?

**Comment by zrss** [comment]
@gyuho 

I added a new unit test file, but not sure whether the file name is appropriate

**Comment by gyuho** [comment]
Defer to @xiang90

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
